"""Shared state definition for the LangGraph research agent."""

from typing import Any, Literal

from typing_extensions import TypedDict


class ResearchState(TypedDict, total=False):
    """State passed between nodes in the research graph.

    Fields:
        research_goal: The original high-level research question from the user.
        sub_queries: List of sub-queries generated by the planner.
        current_query_index: Index of the sub-query currently being processed.
        researcher_attempts: Number of attempts made on the current sub-query (max 3).
        researcher_output: Paper results for the current sub-query from researcher.
        validated_findings: Accumulated validated findings across all sub-queries.
        validation_status: Result of validation for the current sub-query.
        final_report: Final synthesized report from the synthesizer.
        error: Any error that caused the graph to terminate early.
    """

    research_goal: str
    sub_queries: list[str]
    current_query_index: int
    researcher_attempts: int
    researcher_output: list[dict[str, Any]]
    validated_findings: list[dict[str, Any]]
    validation_status: Literal["pending", "valid", "invalid", "failed"]
    final_report: str | None
    error: str | None


def create_initial_state(research_goal: str) -> ResearchState:
    """Create an initial ResearchState with sensible defaults."""
    return ResearchState(
        research_goal=research_goal,
        sub_queries=[],
        current_query_index=0,
        researcher_attempts=0,
        researcher_output=[],
        validated_findings=[],
        validation_status="pending",
        final_report=None,
        error=None,
    )
