"""Synthesizer agent: turns validated findings into a final competitive-landscape-style research report."""

import json
import logging
import re
from typing import Any

from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

from .. import logging_utils
from ..errors import SynthesizerError
from .llm import get_llm

logger = logging.getLogger(__name__)


class SynthesizedReport(BaseModel):
    """Structured output for the synthesized research report."""

    report: str = Field(..., description="The complete markdown report")


SYSTEM_PROMPT = """You are a research synthesis assistant. Your task is to produce a structured, competitive-landscape-style research report from a set of validated findings.

Guidelines:
- ONLY reference papers that are explicitly provided in the validated findings. Do NOT hallucinate or invent papers.
- If no validated findings are provided, produce a clear "insufficient data" report explaining what was attempted, not a fabricated one.
- Structure the report as markdown with the following sections:
  1. **Overview** — A concise summary of the research goal and what was attempted
  2. **Key Themes** — Group related papers by common themes/areas (e.g., "Transformer Architecture Variants", "Benchmark Evaluation Methods", "Efficiency Optimizations")
  3. **Notable Papers** — For each paper: title, authors, one-line relevance note, and arXiv ID/link
  4. **Gaps / Open Questions** — Identify what's missing from the literature based on the findings
- Use professional, analytical tone suitable for a research audience
- Be concise but thorough — this is a competitive landscape report, not an exhaustive literature review
- Link papers using their arXiv IDs (format: `arXiv:2401.12345`)

The input will be a JSON object with:
- research_goal: the original high-level research question
- validated_findings: a list of paper objects, each with arxiv_id, title, authors, abstract, category, published_date, pdf_url

Return ONLY a JSON object with a "report" key containing the markdown string."""


def _parse_llm_json_response(response_content: str) -> SynthesizedReport:
    """Parse LLM response content into SynthesizedReport, with fallback for malformed output."""
    # Try direct JSON parse first
    try:
        data = json.loads(response_content)
        return SynthesizedReport(**data)
    except (json.JSONDecodeError, TypeError, ValueError):
        pass

    # Fallback: try to extract JSON from markdown code blocks or surrounding text
    import re

    json_match = re.search(r"\{.*\}", response_content, re.DOTALL)
    if json_match:
        try:
            data = json.loads(json_match.group(0))
            return SynthesizedReport(**data)
        except (json.JSONDecodeError, TypeError, ValueError):
            pass

    raise SynthesizerError(
        f"Failed to parse LLM response as valid SynthesizedReport: {response_content[:200]}"
    )


def _build_insufficient_data_report(
    research_goal: str, validated_findings: list[dict[str, Any]]
) -> str:
    """Build a clear 'insufficient data' report when no valid findings exist."""
    lines = [
        f"# Research Report: {research_goal}",
        "",
        "## Overview",
        f"This research effort targeted: **{research_goal}**",
        "",
        "## Status: Insufficient Data",
        "",
        "The research process completed, but no validated findings were produced. This typically occurs when:",
        "",
        "- All sub-queries returned zero papers from arXiv",
        "- Papers were found but failed validation (off-topic, low relevance)",
        "- Maximum retry attempts were exhausted for all sub-queries",
        "",
        "## What Was Attempted",
        "",
    ]

    if validated_findings:
        lines.append(f"- **Validated findings collected**: {len(validated_findings)} papers")
        lines.append(
            "- However, these findings either failed validation or were otherwise excluded"
        )
    else:
        lines.append("- **No papers were retrieved or validated** for any sub-query")

    lines.extend(
        [
            "",
            "## Recommendations",
            "",
            "1. **Refine the research goal** — Consider breaking it into more specific, searchable sub-topics",
            "2. **Broaden search terms** — Use more general or alternative keywords for arXiv searches",
            "3. **Check arXiv categories** — Some topics may be in unexpected categories (e.g., cs.LG vs cs.AI)",
            "4. **Try author/venue searches** — If key authors or venues are known, search by those directly",
            "",
            "---",
            "",
            "*Report generated by MCP Research Agent System*",
        ]
    )

    return "\n".join(lines)


async def synthesize_report(
    research_goal: str,
    validated_findings: list[dict[str, Any]],
    llm: ChatOpenAI | None = None,
) -> str:
    """Synthesize validated findings into a final competitive-landscape-style research report.

    Args:
        research_goal: The original high-level research question from the user.
        validated_findings: List of paper dicts with keys: arxiv_id, title, authors, abstract,
            category, published_date, updated_date, pdf_url.
        llm: Optional injected LLM instance for testing. If None, creates one via get_llm().

    Returns:
        A markdown-formatted research report string.

    Raises:
        SynthesizerError: If the LLM call fails or returns unparseable output after retries.
    """
    if llm is None:
        llm = get_llm()

    # Handle empty findings case explicitly
    if not validated_findings:
        logger.info("No validated findings provided, generating insufficient data report")
        return _build_insufficient_data_report(research_goal, validated_findings)

    # Prepare findings for the LLM - include only essential fields to save tokens
    findings_for_llm = []
    for p in validated_findings:
        findings_for_llm.append(
            {
                "arxiv_id": p.get("arxiv_id", ""),
                "title": p.get("title", ""),
                "authors": p.get("authors", []),
                "abstract": p.get("abstract", "")[:500],  # Truncate abstract to save tokens
                "category": p.get("category", ""),
                "published_date": p.get("published_date", ""),
                "pdf_url": p.get("pdf_url", ""),
            }
        )

    structured_llm = llm.with_structured_output(SynthesizedReport)

    messages = [
        ("system", SYSTEM_PROMPT),
        (
            "human",
            f"Research goal: {research_goal}\n\nValidated findings (JSON):\n{json.dumps(findings_for_llm, indent=2)}",
        ),
    ]

    logging_utils.log_event(
        "synthesizer_input",
        {
            "research_goal": research_goal,
            "findings_count": len(findings_for_llm),
        },
    )

    # First attempt: structured output
    try:
        result = await structured_llm.ainvoke(messages)
        if isinstance(result, SynthesizedReport):
            logger.info("Synthesizer report generation succeeded (structured output)")
            logging_utils.log_event(
                "synthesizer_output",
                {"report_length": len(result.report), "status": "success"},
            )
            return result.report
    except Exception as e:
        logger.warning(f"Structured output failed, falling back to manual parse: {e}")

    # Fallback: manual JSON parsing with retry
    max_retries = 2
    last_error = None

    for attempt in range(max_retries):
        try:
            response = await llm.ainvoke(messages)
            content = response.content if hasattr(response, "content") else str(response)
            content_str = content if isinstance(content, str) else json.dumps(content)

            # Try to parse as SynthesizedReport
            try:
                data = json.loads(content_str)
                report = SynthesizedReport(**data)
                logger.info(
                    f"Synthesizer report generation succeeded on fallback attempt {attempt + 1}"
                )
                logging_utils.log_event(
                    "synthesizer_output",
                    {
                        "report_length": len(report.report),
                        "status": "success",
                        "attempt": attempt + 1,
                    },
                )
                return report.report
            except (json.JSONDecodeError, TypeError, ValueError):
                # Try extracting from markdown/surrounding text
                json_match = re.search(r"\{.*\}", content_str, re.DOTALL)
                if json_match:
                    data = json.loads(json_match.group(0))
                    report = SynthesizedReport(**data)
                    logger.info(
                        f"Synthesizer report generation succeeded on fallback attempt {attempt + 1} (extracted)"
                    )
                    logging_utils.log_event(
                        "synthesizer_output",
                        {
                            "report_length": len(report.report),
                            "status": "success",
                            "attempt": attempt + 1,
                        },
                    )
                    return report.report

        except Exception as e:
            last_error = e
            logger.warning(f"Fallback attempt {attempt + 1} failed: {e}")
        else:
            # No exception but parsing failed (invalid JSON structure)
            if last_error is None:
                last_error = ValueError("Failed to parse LLM response as valid JSON")

    raise SynthesizerError(
        f"Failed to synthesize report after {max_retries} fallback attempts. "
        f"Last error: {last_error}"
    ) from last_error
